/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisis;

import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class Principal extends javax.swing.JFrame {
    private ArrayList<clsMinero>mineros=new ArrayList<>();
    private static ArrayList<clsMina>minas=new ArrayList<>();
    static int  botontunel = 0;
    static int botonentrada = 0;
    static int botondeposito = 0;
    static boolean entrada=true;
    static  String material;
    
    public Principal() {
        
        initComponents();  
        
        
    }
     public void botones() {
        ImageIcon face = new ImageIcon(getClass().getResource("../imagenes/icono_camino.png"));
        btnTunel.setIcon(face);
        face = new ImageIcon(getClass().getResource("../imagenes/icono_depositos.png"));
        btnDeposito.setIcon(face);
        face = new ImageIcon(getClass().getResource("../imagenes/icono_entrada.png"));
        btnEntrada.setIcon(face);
        
    }
     
     public static  void notificar(int mina,Point p){
         if (botontunel==1) {
             minas.get(mina).ingresarnuemromapa(p, -1);
             
         }
         else if (botonentrada==1) {
             entrada=false;
             minas.get(mina).ingresarnuemromapa(p,100);
             minas.get(mina).setEntrada(p);
         }else{
             minas.get(mina).ingresarnuemromapa(p,minas.get(mina).depostios.size()+1);
             minas.get(mina).crearDeposito(minas.get(mina).depostios.size()+1,Integer.parseInt(JOptionPane.showInputDialog(null,"ingrese cantidad de material")),p);
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        btnTunel = new javax.swing.JButton();
        btnDeposito = new javax.swing.JButton();
        btnEntrada = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnTunel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTunelActionPerformed(evt);
            }
        });

        btnDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoActionPerformed(evt);
            }
        });

        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Crear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(btnTunel, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(btnDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnTunel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
         material= JOptionPane.showInputDialog(this, "Ingrese material de la mina");
        if (material.equalsIgnoreCase("oro") || material.equalsIgnoreCase("plata") || material.equalsIgnoreCase("cobre")) {
            botones();
            clsMina m = new clsMina(this.minas.size(), material, Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese cantidad maxima de mineros")), Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese tiempo de extraccion")), Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese velocidad de desplazamiento")));
            for (int i = 0; i < 8; i++) {
                for (int j = 0; j < 12; j++) {
                    Casilla c = new Casilla();
                    c.setId(new Point(i, j));
                    c.setMina(minas.size());
                    getContentPane().setLayout(null);
                    getContentPane().add(c);
                    c.setVisible(true);
                    c.setBounds(j * 75 + 280, i * 75, 75, 75);
                    m.casillas.add(c);

                }
            }
            minas.add(m);
        }
        else{
            JOptionPane.showMessageDialog(this,"Material invalido");
        }
        
        
         
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        ImageIcon face = new ImageIcon(getClass().getResource("../imagenes/icono_camino.png"));
//        btnTunel.setIcon(face);
//        face = new ImageIcon(getClass().getResource("../imagenes/icono_depositos.png"));
//        btnDeposito.setIcon(face);
//        face = new ImageIcon(getClass().getResource("../imagenes/icono_entrada.png"));
//        btnEntrada.setIcon(face);
    }//GEN-LAST:event_formWindowOpened

    private void btnTunelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTunelActionPerformed
        botontunel=1;
        botonentrada=0;
        botondeposito=0;
    }//GEN-LAST:event_btnTunelActionPerformed

    private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
        botondeposito=1;
        botonentrada=0;
        botontunel=0;
    }//GEN-LAST:event_btnDepositoActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        
            botonentrada = 1;
            botontunel = 0;
            botondeposito = 0;
        
        
    }//GEN-LAST:event_btnEntradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposito;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnTunel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
